### ISSUE TITLE
Have you considered...

### ISSUE THREAD

**Issue by randycasburn** [RedpointGames/pkgsign#12]
https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5

Many salient points about npm packages and security. Have you consider these in your vision?

**Comment by hach-que** [comment]
This is basically the trust aspect of pkgsign - there's no way for us to actively scan for malicious code within a package you trust, so by default pkgsign trusts nothing.

When you start using a package, it tells you who signed it (in the case of keybase this allows you to also verify identities on Twitter/FB/Reddit/etc.), which allows you to make a determination as to whether you trust the individual or company that signed it.

If it's a dependency of other packages you're pulling in, it'll also tell you what other packages are expecting that individual to sign that package.

However, once you trust an author to sign a given package, you are trusting them to not insert malicious code into it. There's no automated way (other than pinning to exact versions you've audited) to prevent this occurring in a package you trust, even with pkgsign. If you need to know for sure that it's not malicious, audit the dependency's code, fix it to an exact version, and then use "sign on behalf of" to lock the content of all the files in that dependency to exactly match (ensuring even if a package with the same version signed by the trusted author appears, pkgsign will alert you to any changes).

Most of our focus is on registries, other packages or other software tampering with dependencies, or people taking malicious control of a package name and serving up a compromised version of a package (for example, if someone takes over your NPM account and uploads a new version with malicious code). pkgsign will actively protect you from those scenarios.

**Comment by randycasburn** [comment]
Thanks for the thorough response. I was having difficulty understanding the nature of your scope. You've done a superb job at explaining. Thanks and best of luck with your important efforts here. Respectfully.
