### ISSUE TITLE
Unclear prompt message when asking for trust

### ISSUE THREAD

**Issue by ilesinge** [RedpointGames/pkgsign#5]
Currently, when asking for trust of an identity, the prompt is waiting for "true", "false", "t", "f", but it is unclear and not really aligned with common usage. As a user, I personally expect "yes", "no","y","n".

![verify](https://user-images.githubusercontent.com/501674/35182126-05e6060c-fdcf-11e7-93fc-4c52c21368e0.png)

As https://github.com/flatiron/prompt doesn't allow to change the expected boolean input values, a simple solution would be to include explicit instructions (type "true" or "false").
But https://github.com/flatiron/prompt doesn't seem to be maintained, and I could not find a way to prevent the totally unclear error "Invalid input for undefined".

Another solution would be to use https://github.com/SBoudrias/Inquirer.js
It has another advantage in that it makes the questions stand out in a terminal that supports ansi codes:

![verify-inquirer](https://user-images.githubusercontent.com/501674/35182199-3d7b0ecc-fdd0-11e7-97de-c10d7cb1f9d6.png)

**Comment by hach-que** [comment]
Resolved in the `dev` branch and will be released as part of `0.2.0`.
