### ISSUE TITLE
Suggestion: Default to current directory on pkgsign verify

### ISSUE THREAD

**Issue by oiime** [RedpointGames/pkgsign#9]
following common practice with `npm` and `yarn` `pkgsign verify` with no additional arguments should assume the current directory or closest parent directory with a `package.json` is the intended target

**Comment by hach-que** [comment]
This is a reasonable enhancement, so I'll target it for 0.2.0.

**Comment by hach-que** [comment]
This is now in the `dev` branch and will be released as part of `0.2.0`.
